swagger: '2.0'

################################################################################
#                              API Information                                 #
################################################################################
info:
  version: '1.0'
  title: CDS Hooks REST API
host: cds-service-example.herokuapp.com
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json

################################################################################
#                                           Paths                              #
################################################################################
paths:
  /.well-known/cds-services:
    get:
      description: Returns information on all CDS services offered by this CDS Provider
      responses:
        200:
          description: Information for all CDS services offered by this CDS Provider
          schema:
            $ref: '#/definitions/CDS Service Information'

  /cds-services/{service-name}:
    post:
      description: Invokes a CDS service
      parameters:
        - name: service-name
          in: path
          description: Name of the CDS service
          required: true
          type: string
        - name: request
          in: body
          description: The body of CDS service request
          required: true
          schema:
            $ref: '#/definitions/CDS Request'
      responses:
        200:
          description: An array of cards
          schema:
            $ref: '#/definitions/CDS Response'


################################################################################
#                                 Definitions                                  #
################################################################################
definitions:
  CDS Service Information:
    type: object
    properties:
      services:
        type: array
        items:
           $ref: '#/definitions/CDS Service'

  CDS Service:
    type: object
    properties:
      hook:
        $ref: '#/definitions/HookCoding'
      name:
        type: string
      description:
        type: string
      id:
        type: string
      preFetch:
        type: array
        items:
          type: object

  CDS Request:
    type: object
    properties:
      hook:
        $ref: '#/definitions/Hook'
      hookInstance:
        type: string
        format: uuid
      fhirServer:
        type: string
        format: url
      oauth:
        type: object
      redirect:
        type: string
      user:
        type: object
      patient:
        type: object
      encounter:
        type: object
      context:
        type: array
        items:
          type: object
      preFetchData:
        type: object

  HookCoding:
    type: object
    properties:
      system:
        type: string
      code:
        type: string

  CDS Response:
    type: object
    properties:
      cards:
        type: array
        items:
          $ref: '#/definitions/Card'
      decisions:
        type: object

  Card:
    type: object
    properties:
      summary:
        type: string
      detail:
        type: string
      indicator:
        type: string
        enum:
          - success
          - info
          - warning
          - hard-stop
      source:
        $ref: '#/definitions/Source'
      suggestions:
        type: array
        items:
          $ref: '#/definitions/Suggestion'
      links:
        type: array
        items:
          $ref: '#/definitions/Link'

  Hook:
    type: string
    enum:
      - patient-view
      - medication-prescribe
      - order-review

  Source:
    type: object
    properties:
      name:
        type: string
      url:
        type: string
        format: url

  Link:
    type: object
    properties:
      label:
        type: string
      url:
        type: string
        format: url

  Suggestion:
    type: object
    properties:
      label:
        type: string
      create:
        type: array
        items:
          type: object
      delete:
        type: array
        items:
          type: object
