site_name: CDS Hooks

theme:
  name: 'material'
  logo: 'images/logo-square.png'
  palette:
    primary: 'blue'
    accent: 'blue'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/cds-hooks'

pages:
- Overview: 'index.md'
- Spec: 'spec.md'
- Hooks: 'hooks.md'
- Examples: 'examples.md'
- Community: 'community.md'

repo_url: 'https://github.com/cds-hooks/docs'
